name: Feature Request
description: Request something to be added to Vs. WinMario
labels: ["Type: request","Awaits labeling"]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **Vs. WinMario** engine?
    validations:
      required: true
